# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local

exp_name: run
phase: test

#model
model_type: 'single'
model: 'GRUNet'

#Dataset
negative_sampling_rate:
duration: 5760
downsample_rate:
upsample_rate:
batch_size: 32

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
score_th: 0.02
distance: 120

label:
  offset: 10
  sigma: 3
  labels:
    - "awake"
    - "event_onset"
    - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "hour_sin"
  # - "hour_cos"
