# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${exp_name}/${hydra.job.name}
  sweep:
    dir: ${dir.output_dir}/${exp_name}/${hydra.job.name}
    subdir: run${hydra.job.num}

exp_name: run
defaults:
  - _self_
  - dir: local
  - model: dual

series_parquet: test.parquet
event_csv: test_events.csv
phase: test

#Dataset
duration: 5760
downsample_rate: 2
batch_size: 32

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
score_th: 0.02
distance: 120

label:
  offset: 10
  sigma: 3
  labels:
    - "awake"
    - "event_onset"
    - "event_wakeup"

# feature
features: 
  - "anglez"
  - "enmo"
  - "lids"
  - 'weekday'
  - 'signal_onset'
  - 'signal_awake'
  - 'hour'
  # - 'enmo_rolling_mean'
  # - 'enmo_rolling_max'
  # - 'enmo_rolling_std'
  # - 'anglez_rolling_mean'
  # - 'anglez_rolling_max'
  # - 'anglez_rolling_std'
  # - 'enmo_prev_diff_rolling_mean'
  # - 'enmo_prev_diff_rolling_max'
  # - 'anglez_prev_diff_rolling_mean'
  # - 'anglez_prev_diff_rolling_max'
  # - 'anglez_mad'
  # - 'enmo_mad'
  - 'anglez_sin'
  # - 'anglez_cos'
  # - 'anglez_tan'

  # - "month_sin" 
  # - "month_cos"
  # - "hour_sin"
  # - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"
