# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

exp_name: dummy
defaults:
  - _self_
  - dir: local
#model
model_type: 'single'
model: 'GRUNet'
hidden_units: 128
n_layers: 4

#fit
epochs: 30

metric:
 AP_threshold: 0.0

#Dataset
negative_sampling_rate:
duration: 5760
downsample_rate:
upsample_rate:
batch_size: 32

augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

label:
  offset: 10
  sigma: 3
  labels:
    - "awake"
    - "event_onset"
    - "event_wakeup"

phase: train

# feature
features: 
  - "anglez"
  - "enmo"
  # - "month_sin" 
  # - "month_cos"
  # - "hour_sin"
  # - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"