# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${exp_name}/${hydra.job.name}
  sweep:
    dir: ${dir.output_dir}/${exp_name}/${hydra.job.name}
    subdir: run${hydra.job.num}

exp_name: run
defaults:
  - _self_
  - dir: local
#model
model_type: 'single'
model: 'GRUNet'
hidden_units: 64
n_layers: 4
finetune: 0
dropout_rate: 0.0
gru_dropout_rate: 0.2

#fit
epochs: 30

metric:
 AP_threshold: 0.0

#Dataset
duration: 5760
downsample_rate:
upsample_rate:
batch_size: 64

augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

label:
  offset: 10
  sigma: 3
  labels:
    - "awake"
    - "event_onset"
    - "event_wakeup"

phase: train

# feature
features: 
  - "anglez"
  - "enmo"
  # - "month_sin" 
  # - "month_cos"
  # - "hour_sin"
  # - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"