src_dir: /home/lyu/AI/CMI/src
data_dir: /home/lyu/AI/CMI/data/child-mind-institute-detect-sleep-states
reduced_data_dir: /home/lyu/AI/CMI/data/detect-sleep-states-memory-decrease
processed_dir: /home/lyu/AI/CMI/data/preprocessed_data
output_dir: /home/lyu/AI/CMI
model_dir: /home/lyu/AI/CMI/src/models
model_save_dir: /home/lyu/AI/CMI/src/models/saved_models
sub_dir:
tensorboard_logs: /home/lyu/AI/CMI/run/tensorboard_logs